version: '3.3'

services:
  nginx:
    build:
      context: ./nginx/proxy
      dockerfile: Dockerfile
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./php/wp/src:/app/wp
    depends_on:
      - backend
      - frontend
    networks:
      - backend
      - frontend

  frontend:
    image: nginx:1.15.2-alpine
    restart: always
    volumes:
      - ./holding:/usr/share/nginx/html/:ro
    networks:
      - frontend

  backend:
    build:
      context: ./nginx/backend
      dockerfile: Dockerfile
    volumes:
      - ./php/wp/src:/app/wp
    depends_on:
      - php
    restart: always
    networks:
      - backend

  php:
    build: ./php
    env_file: ./php/.env
    volumes:
      - ./php/wp/src:/app/wp
    expose:
      - 9000
    restart: always
    networks:
      - backend

networks:
  backend:
    external:
      name: backend
  frontend:
    external:
      name: frontend

volumes:
  wp-volume:
