version: '3.3'

services:
  nginx:
    build:
      context: ./nginx/backend
      dockerfile: Dockerfile-dev
    ports:
      - '80:80'
    volumes:
      - ./php/wp/src:/app
    depends_on:
      - php
      - mysql
    restart: always
    networks:
      - backend

  php:
    build: ./php
    env_file: ./php/.env
    volumes:
      - ./php/vendor:/app/vendor
      - ./php/wp/src:/app
    expose:
      - 9000
    depends_on:
      - mysql
      - composer
    restart: always
    networks:
      - backend

  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - ./php:/app

  mysql:
    build: ./mysql
    env_file: ./mysql/.env
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db-data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    restart: always

    networks:
      - backend

networks:
  backend:
    external:
      name: backend

volumes:
  wp-volume:
