version: '3.3'

services:
  nginx:
    build:
      context: ./nginx/backend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./php/wp/src:/app
    depends_on:
      - php
    restart: always
    networks:
      - backend

  php:
    build: ./php
    env_file: ./php/.env
    volumes:
      - ./php/wp/src:/app
    expose:
      - 9000
    restart: always
    networks:
      - backend

networks:
  backend:
    external:
      name: backend

volumes:
  wp-volume:
