version: '3.3'

services:
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - '80:80'
    volumes:
      - ./php/wp/src:/app/src
    depends_on:
      - php
    restart: always
    networks:
      - touchrugby

  php:
    build:
      context: .
      target: php
    env_file: ./php/.env
    volumes:
      - ./php/vendor:/app/vendor
      - ./php/wp/src:/app/src
    depends_on:
      - mysql
    restart: always
    networks:
      - touchrugby

  mysql:
    build:
      context: .
      target: mysql
    env_file: ./mysql/.env
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    volumes:
      - touchrugby-dbdata:/var/lib/mysql
    restart: always
    networks:
      - touchrugby

networks:
  touchrugby:
    external:
      name: touchrugby

volumes:
  touchrugby-dbdata:
     external: true
