version: '3.3'

services:
  php:
    image: touchrugby-php:latest
    env_file: ./php/.env
    restart: always
    volumes:
    - ./php/wp/src/wp-content:/app/src/wp-content
    networks:
      - touchrugby

  nginx:
    image: touchrugby-nginx:latest
    ports:
      - '80:80'
    depends_on:
      - php
    restart: always
    networks:
      - touchrugby

networks:
  touchrugby:
    external:
      name: touchrugby
